import Head from "next/head";
import { GetServerSideProps } from "next";

export default function HomeP() {
  return (
    <>
      <Head>
        <title>MKS_frontend_challenge</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
}

export const getServerSideProps: GetServerSideProps = async (ctx) => {
  return {
    redirect: {
      destination: "/home",
      permanent: false,
    },
  };
};
